@startuml
@startgantt
[Elicit requirements] requires 9 days and is colored in LightBlue
[Method selection] requires 9 days and is colored in LightGreen
[Evaluate risks] requires 31 days and is colored in LightPink
[Plan Architecture] starts D+6
[Plan Architecture] ends  D+15
[Plan Architecture] is colored in Khaki
[Refine Architecture] starts D+14
[Refine Architecture] ends D+20
[Refine Architecture] is colored in Khaki
[Create Game & Menu screens] starts D+12
[Create Game & Menu screens] ends D+15
[Create Game & Menu screens] is colored in Purple
[Create Map] starts D+12
[Create Map] ends D+15
[Create Map] is colored in Indigo
[Create basic avatar] starts D+13
[Create basic avatar] ends D+17
[Create basic avatar] is colored in Orchid
[Avatar moving around map] starts D+17
[Avatar moving around map] ends D+20
[Avatar moving around map] is colored in MediumOrchid
[Avatar can complete events] starts D+20
[Avatar can complete events] ends D+25
[Avatar can complete events] is colored in MediumSlateBlue
[Nice to have features e.g sound] starts D+25
[Nice to have features e.g sound] ends D+30
[Nice to have features e.g sound] is colored in Indigo
@endgantt
@enduml