@startuml
@startgantt
project starts the 14th February 2024
[Team Organisation] starts 2024-02-14
[Team Organisation] ends 2024-02-21
[Team Organisation] is colored in Green
[Method selection] starts 2024-02-14
[Method selection] ends 2024-02-28
[Method selection] is colored in LightGreen
[Requirements Gathering] starts 2024-02-21
[Requirements Gathering] ends 2024-03-06
[Requirements Gathering] is colored in LightBlue
[Evaluate risks] starts 2024-02-14
[Evaluate risks] ends 2024-03-21
[Evaluate risks] is colored in LightPink
[Plan Architecture] starts 2024-02-21
[Plan Architecture] ends  2024-03-13
[Plan Architecture] is colored in Khaki
[Refine Architecture] starts 2024-03-06
[Refine Architecture] ends 2024-03-21
[Refine Architecture] is colored in Khaki
[Create Game & Menu screens] starts 2024-02-28
[Create Game & Menu screens] ends 2024-03-02
[Create Game & Menu screens] is colored in Purple
[Create Map] starts 2024-02-28
[Create Map] ends 2024-03-07
[Create Map] is colored in Salmon
[Create basic avatar] starts 2024-03-03
[Create basic avatar] ends 2024-03-07
[Create basic avatar] is colored in Orchid
[Avatar moving around map] starts 2024-03-07
[Avatar moving around map] ends 2024-03-09
[Avatar moving around map] is colored in MediumOrchid
[Avatar completing events] starts 2024-03-10
[Avatar completing events] ends 2024-03-13
[Avatar completing events] is colored in MediumSlateBlue
[Nice to have features] starts 2024-03-14
[Nice to have features] ends 2024-03-21
[Nice to have features] is colored in Lavender
[Slack for overruns] starts 2024-03-14
[Slack for overruns] ends 2024-03-21
[Slack for overruns] is colored in Tomato
@endgantt
@enduml