name: Java CI with Gradle
on:
  push:
    branches: ["main", "cleanup-directory"]
  pull_request:
    branches: ["main"]
jobs:
  build:
    runs-on: ubuntu-22.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@v3
      - name: Set-up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
      - name: Build with Gradle
        uses: gradle/gradle-build-action@v3
        with:
          arguments: build jacocoTestReport
          build-root-directory: game
      - name: Upload JaCoco coverage report as a workflow artifact
        uses: actions/upload-artifact@v3.1.1
        with:
          name: jacoco-report
          path: game/build/reports/jacoco/test/html/